#!/bin/sh
set -e

# Synergia Client Installer
# Generated by the Synergia Manager

BASE_URL="{{BASE_URL}}"
WORKER_KEY="{{WORKER_KEY}}"

# Detect OS
OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
case "$OS" in
  darwin) OS="darwin" ;;
  linux)  OS="linux" ;;
  *)      echo "Unsupported OS: $OS"; exit 1 ;;
esac

# Detect architecture
ARCH="$(uname -m)"
case "$ARCH" in
  x86_64|amd64) ARCH="amd64" ;;
  arm64|aarch64) ARCH="arm64" ;;
  *)            echo "Unsupported architecture: $ARCH"; exit 1 ;;
esac

BINARY="synergia-client"
INSTALL_DIR="$HOME/.local/bin"
DATA_DIR="$HOME/.local/share/synergia"
APP_BUNDLE="$HOME/Applications/Synergia.app"

echo "Synergia Client Installer"
echo "========================="
echo "OS:   $OS"
echo "Arch: $ARCH"
echo ""

# Create directories
mkdir -p "$INSTALL_DIR"
mkdir -p "$DATA_DIR"

# Download the patched binary
echo "Downloading synergia-client for $OS/$ARCH..."
curl -sSL -o "$INSTALL_DIR/$BINARY" "$BASE_URL/download/$OS/$ARCH"
chmod +x "$INSTALL_DIR/$BINARY"

# macOS: clear Gatekeeper quarantine and wrap in a .app bundle so
# double-clicking opens the tray icon without spawning a terminal window.
if [ "$OS" = "darwin" ]; then
  xattr -dr com.apple.quarantine "$INSTALL_DIR/$BINARY" 2>/dev/null || true

  mkdir -p "$APP_BUNDLE/Contents/MacOS"
  cp "$INSTALL_DIR/$BINARY" "$APP_BUNDLE/Contents/MacOS/synergia-client"
  chmod +x "$APP_BUNDLE/Contents/MacOS/synergia-client"
  cat > "$APP_BUNDLE/Contents/Info.plist" << 'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleExecutable</key>   <string>synergia-client</string>
  <key>CFBundleIdentifier</key>  <string>net.synergia.client</string>
  <key>CFBundleName</key>         <string>Synergia</string>
  <key>CFBundlePackageType</key>  <string>APPL</string>
  <key>CFBundleVersion</key>      <string>1</string>
  <key>LSUIElement</key>          <true/>
</dict>
</plist>
PLIST
  echo "App bundle created at $APP_BUNDLE — double-click to launch (tray only, no terminal)"
fi

echo "Installed to $INSTALL_DIR/$BINARY"

# Save worker key if provided
if [ -n "$WORKER_KEY" ]; then
  echo "$WORKER_KEY" > "$DATA_DIR/worker-key"
  echo "Worker key saved."
fi

# Set up auto-start
if [ "$OS" = "darwin" ]; then
  PLIST_DIR="$HOME/Library/LaunchAgents"
  PLIST_FILE="$PLIST_DIR/com.synergia.client.plist"
  mkdir -p "$PLIST_DIR"
  # Point the LaunchAgent at the binary inside the .app bundle so it runs
  # as a proper background app (tray only, no terminal window).
  LAUNCH_BIN="$APP_BUNDLE/Contents/MacOS/synergia-client"
  cat > "$PLIST_FILE" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>com.synergia.client</string>
  <key>ProgramArguments</key>
  <array>
    <string>$LAUNCH_BIN</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>StandardOutPath</key>
  <string>$DATA_DIR/stdout.log</string>
  <key>StandardErrorPath</key>
  <string>$DATA_DIR/stderr.log</string>
</dict>
</plist>
EOF
  # Unload first so a running instance is stopped and the new binary takes effect.
  launchctl unload "$PLIST_FILE" 2>/dev/null || true
  launchctl load   "$PLIST_FILE" 2>/dev/null || true
  echo "Auto-start configured (macOS LaunchAgent)."
elif [ "$OS" = "linux" ]; then
  SYSTEMD_DIR="$HOME/.config/systemd/user"
  SERVICE_FILE="$SYSTEMD_DIR/synergia-client.service"
  mkdir -p "$SYSTEMD_DIR"
  cat > "$SERVICE_FILE" << EOF
[Unit]
Description=Synergia Client
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=$INSTALL_DIR/$BINARY
Restart=always
RestartSec=5

[Install]
WantedBy=default.target
EOF
  systemctl --user daemon-reload 2>/dev/null || true
  systemctl --user enable synergia-client 2>/dev/null || true
  systemctl --user restart synergia-client 2>/dev/null || true
  echo "Auto-start configured (systemd user service)."
fi

echo ""
echo "Done! Synergia client is running."
echo "Dashboard: http://localhost:9876"

# Ensure ~/.local/bin is in PATH
case ":$PATH:" in
  *":$INSTALL_DIR:"*) ;;
  *) echo ""; echo "NOTE: Add $INSTALL_DIR to your PATH if not already there." ;;
esac
